### ISSUE TITLE
Is there any plan to support chinese?

### ISSUE THREAD

**Issue by guduxingzou** [JasonKessler/scattertext#10]
This is a very usefull repo.Is there any plan to support Chinese?  thanks very much!
谢谢您的分享！

**Comment by JasonKessler** [comment]
Thank you, and you're in luck. Scattertext already has Chinese support. See https://github.com/JasonKessler/scattertext/blob/master/demo_chinese.py for an example of how to analyze Chinese documents. 

Make sure you use Python 3, since Chinese is supported in the Python 2 version.

**Comment by guduxingzou** [comment]
wawo ths you

**Comment by guduxingzou** [comment]
use：
import codecs
codecs.open('demo.html','w',encoding='utf-8',errors='ignore').write(html)
replace：
open('./demo_chinese.html', 'w').write(html.encode('utf-8'))

 open with Firefox and sougou（搜狗浏览器）

envi:   win7 python3.5
