### ISSUE TITLE
Is it possible to remove stopwords without Spacy?

### ISSUE THREAD

**Issue by gskarp** [JasonKessler/scattertext#105]
I have a problem in using Spacy lately, and I tried to use scattertext without Spacy, as described in the relevant .py archive. Due to the large amount of words, it takes a long time and memory to load. I wonder whether it is possible to remove stopwords without Spacy?

**Comment by JasonKessler** [comment]
The stoplisting is independent of spaCy.  If a visualization is taking a long time to load in the browser, I'd run <corpus>.compact(st.AssociationCompactor(2000)), which reduces the number of terms in the visualization to 2000.
