### ISSUE TITLE
How to have the Scattertext without showing collocation?

### ISSUE THREAD

**Issue by Lipahak** [JasonKessler/scattertext#106]
## Steps to Reproduce
I have these steps to generate a Scattertext with my data:

```
# Here is the code snippet
import scattertext as st
from pprint import pprint
from scattertext import SampleCorpora, PhraseMachinePhrases, dense_rank, RankDifference, AssociationCompactor, produce_scattertext_explorer
from scattertext.CorpusFromPandas import CorpusFromPandas
import spacy
nlp = spacy.load("en_core_web_sm")

# corpus
corpus = st.CorpusFromPandas(df,   #############edit              
                            category_col='tag', 
                            text_col='text',
                            nlp=nlp).build()
# textscatter plot
path1="xxx"
html = st.produce_scattertext_explorer(corpus,
          category='Y',
          category_name='A',
          not_category_name='B',
          width_in_pixels=1000,
          metadata=df['text_remove'])    ##############edit

```

## Expected behavior

There are couple of words showing in collocation. 
I expected words scattering word by word without collocation.
How could I avoid it?
Deeply appreciate your kind answer.
![image](https://user-images.githubusercontent.com/85079403/147877864-6f1089d4-90cd-4af1-8a30-ce0b587a27ff.png)

**Comment by JasonKessler** [comment]
Run corpus=corpus.get_unigram_corpus(). This will remove bigrams.

**Comment by JasonKessler** [comment]
The colors correspond to the scaled f scores. Please add these as a discussion item instead of an issue.
