### ISSUE TITLE
Corpus size too large

### ISSUE THREAD

**Issue by yshi2016** [JasonKessler/scattertext#110]
Hello, I used a dataset with more than 1 million rows and the output size is 572MB with the output like below
<img width="925" alt="image" src="https://user-images.githubusercontent.com/43195541/168325104-0080d984-fb63-4177-a7c7-43e141bbbc23.png">
I am wondering if this is due to the file being too large? Is there a method builtin scatter text to accommodate the size issue, or should we try sampling a subset of the original data? Thank you!

**Comment by JasonKessler** [comment]
You can try to set the `max_docs_per_category` parameter of `produce_scattertext_explorer` to limit the number of documents stored per category. Plotting positions would still be calculated over the whole corpus.  Otherwise, your best bet is to downsample the data you use to create your corpus.
