### ISSUE TITLE
Lack of words in one category

### ISSUE THREAD

**Issue by yshi2016** [JasonKessler/scattertext#111]
Hi! I ran scattertext for two categories reddit and quora, with max_docs_per_category=30000, however, the caption only shows that there are 30000 docs from reddit, and there is nothing for quora, though it ran successfully. In which case would this happen, is it due to quora corpus being too small compared to the other? Thank you!
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/43195541/168729981-cdf4a40c-73e6-4ece-ba2f-675f612578b3.png">

**Comment by JasonKessler** [comment]
If you upload the code, source data and produced visualization, someone maybe can look into this. Otherwise, there's not enough information to investigate.
