### ISSUE TITLE
How to make points in the chart bigger? 

### ISSUE THREAD

**Issue by mvitha** [JasonKessler/scattertext#113]
Is there a way to make the individual points in the chart bigger? 

The idea would be to use the minimum_term_frequency to lower the number of terms that appear in the viz, and then make the font and bubble size bigger. 

Any help would be much appreciated!

**Comment by JasonKessler** [comment]
Not currently.

**Comment by mikkokotila** [comment]
You can easily achieve this by programmatically manipulating the HTML after it has been produced (before rendering it).

**Comment by mikkokotila** [comment]
Better yet, just add something similar to this as to your liking in terms of how you want to style your html before saving it to a file:

```
    html = re.sub(r'body {[^}]*}', 
                  "body {\n  font: 20px;\n  font-family: 'Noto Serif Tibetan', serif;\n  background-color: #f0f0f5;\n}", 
                  html)

    html = re.sub(r'\.attr\(\'font-size\', \'10px\'\)', 
                  ".attr('font-size', '18px')", 
                  html)
```
