### ISSUE TITLE
Trouble met when using chinese_nlp

### ISSUE THREAD

**Issue by geekinglcq** [JasonKessler/scattertext#16]
Thanks for this cool job you have done first!
Here I meet a problem when using `chinese_nlp`.
If I have `import jieba` in my own code, and then `data['text'] = data['text'].apply(chinese_nlp)`, python will throw an error like followings:
```
         59   if 'jieba' not in sys.modules:
         60      jieba = __import__('jieba')
---->    61   return jieba.cut
         62

NameError: name 'jieba' is not defined
```
However if I don't `import jieba` in my code, the problem won't occur.

## Your Environment

* Operating System: deepin & win
* Python Version Used: 3.5
* Scattertext Version Used: lastest
* Environment Information:
* Browser used (if an HTML error): chrome

**Comment by JasonKessler** [comment]
Thanks for reporting this! Taking a look right now.

**Comment by JasonKessler** [comment]
I'm pushing out 2.9.10 as we speak.  This should resolve the issue.
