### ISSUE TITLE
Scattertext not found when using Ipython notebook in python3.6

### ISSUE THREAD

**Issue by jennxf** [JasonKessler/scattertext#17]
I installed scatter text using` conda install -c conda-forge scattertext` and when i open python in the terminal to import the package it works fine. When I try your tutorial notebook part 1 though, i keep getting an error `ImportError: No module named 'scattertext'`

The ipython notebook is using python3 

Im on mac 10.12.6.
scattertext==0.0.2.9.9
python version 3.6.2

**Comment by JasonKessler** [comment]
Hmm.  I just installed Scattertext using `conda install -c conda-forge scattertext` on a fresh virtual environment, and it installed just fine.  

Are you sure you're using the same kernel that was active when you installed Scattertext?
