### ISSUE TITLE
Clean_function docstring unclear

### ISSUE THREAD

**Issue by David-Herman** [JasonKessler/scattertext#21]
https://github.com/JasonKessler/scattertext/blob/e2cfa882ed1d456f239ec8148453fd8452091371/scattertext/CorpusFromPandas.py#L20

Hello,

I wanted to comment that the doc string on the clean function may be unclear. I understood it to be post-tokenization rather than the per document raw text. Perhaps the docstring could be improved to clarify this point.

Thank you

**Comment by JasonKessler** [comment]
Sure.  Fix will come in the next 0.0.2.13.
