### ISSUE TITLE
An unexpected keyword argument 'corpus_for_empath'

### ISSUE THREAD

**Issue by don-tpanic** [JasonKessler/scattertext#30]
First of all, thanks for the great tool. I am having this issue while following the tutorial (Visualizing Empath topics and categories):
TypeError: produce_scattertext_explorer() got an unexpected keyword argument 'corpus_for_empath'

**Comment by JasonKessler** [comment]
Good catch.  There was an error in the example, "corpus_for_empath" should have been "category". I updated the example in the readme.
