### ISSUE TITLE
Extract coordinates from produce_scattertext_explorer()

### ISSUE THREAD

**Issue by ebaggott** [JasonKessler/scattertext#35]
I'm using Scattertext on Python 2.7. I would like to save the x coordinates and y coordinates that are used to plot produce_scattertext_explorer() for later use in a statistical program. How can I do that? Many thanks, this is great!

**Comment by JasonKessler** [comment]
Just pass return_data=True into produce_scattertext_explorer. You’ll see a dictionary containing a sh sub-dictionary listing terms and various cryptic values. The ox and oy values indicate a term’s position on the chart. 

I’m currently without access to a computer, and will stay out of pocket until around August 3. 

Best of luck, 
Jason

**Comment by ebaggott** [comment]
Thank you! This worked. For reference, return_data=True only worked for me on Python 3, not on Python 2.
