### ISSUE TITLE
Scattertext Slack

### ISSUE THREAD

**Issue by theotheo** [JasonKessler/scattertext#4]
Hi there! 
At first, thanks for this impressive project. 
But I have a few questions and as I understand correctly it would be good to ask it in the slack.  
So how to get an access to it?

**Comment by JasonKessler** [comment]
Hi @theotheo ,
Thanks for the kudos, and appreciate you looking into the project.  

I'm realizing that Slack isn't the best way of fielding questions, and have migrated to [Gitter Scattertext](https://gitter.im/scattertext/Lobby?source=orgpage).

This will be on the Readme in a few minutes when I push out the next change.

Of course, feel free to ask your question here, or as another issue. 
Jason

**Comment by theotheo** [comment]
Thank you! And yes, I agree that Slack isn't the best place for such kind of purpose.
