### ISSUE TITLE
How to use scattertext with sentencepiece

### ISSUE THREAD

**Issue by aman5319** [JasonKessler/scattertext#48]
How do I use this library with [sentencepiece](https://github.com/google/sentencepiece).

**Update**
After going through the code base I realized that the tokenizer used for this library should give POS tags, whereas sentencepiece does not. It's just a tokenizer. 
 Is there any workaround??
Since I am trying to use this library to visualize Hindi language data.

**Comment by JasonKessler** [comment]
I've added a SentencePiece capability to the new version of Scattertext. See https://github.com/JasonKessler/scattertext#visualizing-sentencepiece-tokens for an example of how to use it.
