### ISSUE TITLE
Future warning: sklearn.feature_extraction.stop_words module is deprecated

### ISSUE THREAD

**Issue by Nov05** [JasonKessler/scattertext#49]
Scattertext now will trigger the following future warning message.

C:\Users\*\.virtualenvs\django-tally-QTYVOJb0\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The **sklearn.feature_extraction.stop_words module is deprecated** in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_extraction.text. Anything that cannot be imported from sklearn.feature_extraction.text is now part of the private API.

## Your Environment
* Python Version Used: Python 3.6
* Scikit-Learn Version Used 0.22.1
* Scattertext Version Used: 0.0.2.56

**Comment by JasonKessler** [comment]
This is fixed in 0.0.2.57.
