### ISSUE TITLE
Getting error while building Empath

### ISSUE THREAD

**Issue by richliao** [JasonKessler/scattertext#5]
Hi,

I'm getting following error while running the sample code for Empath, while there's no error running term frequency.

from scattertext import FeatsFromOnlyEmpath

corpus = st.CorpusFromParsedDocuments(convention_df,
                                      category_col='party',
                                      feats_from_spacy_doc=st.FeatsFromOnlyEmpath(),
                                      parsed_col='text').build()

TypeError                                 Traceback (most recent call last)
<ipython-input-30-b849fb8366e3> in <module>()
      4                                       category_col='party',
      5                                       feats_from_spacy_doc=st.FeatsFromOnlyEmpath(),
----> 6                                       parsed_col='text').build()

/Users/k25214/anaconda/lib/python2.7/site-packages/scattertext/CorpusFromParsedDocuments.pyc in build(self)
     53                                     self._metadata_idx_store,
     54                                     self._parsed_col,
---> 55 		                    self._category_col)
     56 
     57         def _get_y_and_populate_category_idx_store(self):

/Users/k25214/anaconda/lib/python2.7/site-packages/scattertext/ParsedCorpus.pyc in __init__(self, df, X, mX, y, term_idx_store, category_idx_store, metadata_idx_store, parsed_col, category_col, unigram_frequency_path)
     36                 # TermDocMatrix.__init__(self, X, y, term_idx_store,
     37                 #                       category_idx_store, unigram_frequency_path)
---> 38 		super(ParsedCorpus, self).__init__(X, mX, y, term_idx_store, category_idx_store,
     39                                                    metadata_idx_store,
     40                                                    self._df[self._parsed_col],

TypeError: super() argument 1 must be type, not classobj

**Comment by JasonKessler** [comment]
Thanks for reporting this!  

I just put up a new version of Scattertext, and it should contain a fix for this issue.

**Comment by richliao** [comment]
Thanks Jason,

Somehow I still can't get it working.

I have git clone your latest file in a folder and run "python demo_empath.py"
first error I have to fix is
 File "demo_empath.py", line 31, in <module>
    main()
  File "demo_empath.py", line 17, in main
    feats_from_spacy_doc=FeatsFromOnlyEmpath()).build()
  File "/Users/k25214/python/nlp/scattertext/scattertext/CorpusFromParsedDocuments.py", line 44, in build
    self._df.apply(self._add_to_x_factory, axis=1)
  File "/Users/k25214/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 4152, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/Users/k25214/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 4248, in _apply_standard
    results[i] = func(v)
  File "/Users/k25214/python/nlp/scattertext/scattertext/CorpusFromParsedDocuments.py", line 65, in _add_to_x_factory
    for meta, val in self._feats_from_spacy_doc.get_doc_metadata(parsed_text).items():
  File "/Users/k25214/python/nlp/scattertext/scattertext/features/FeatsFromOnlyEmpath.py", line 10, in get_doc_metadata
    return super(FeatsFromOnlyEmpath, self).get_doc_metadata(doc, prefix=prefix)
  File "/Users/k25214/python/nlp/scattertext/scattertext/features/FeatsFromSpacyDocAndEmpath.py", line 39, in get_doc_metadata
    for empath_category, score in self._empath_analyze_function(str(doc)).items():
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 369: ordinal not in range(128)

I got it fixed by converting to ascii and ignoring unicode. However I am still stuck at the error message as above

Traceback (most recent call last):
  File "demo_empath.py", line 34, in <module>
    main()
  File "demo_empath.py", line 20, in main
    feats_from_spacy_doc=FeatsFromOnlyEmpath()).build()
  File "/Users/k25214/python/nlp/scattertext/scattertext/CorpusFromParsedDocuments.py", line 55, in build
    self._category_col)
  File "/Users/k25214/python/nlp/scattertext/scattertext/ParsedCorpus.py", line 38, in __init__
    super(ParsedCorpus, self).__init__(X, mX, y, term_idx_store, category_idx_store,
TypeError: super() argument 1 must be type, not classobj

Any dependency packages/path I need to fix? 

Third, python demo.py returns a blank chart even the term frequency corpus seem right. See attached.

<img width="1182" alt="screen shot 2017-03-08 at 4 41 19 pm" src="https://cloud.githubusercontent.com/assets/16064756/23725782/e68d7488-041f-11e7-8f2b-63900f4c6933.png">

**Comment by JasonKessler** [comment]
Damn.  It looks like this is an issue in Python2.  I'll look into getting this fixed, but could you run the tool in Python3.5+ for now?

**Comment by richliao** [comment]
You are right. Everything works fine under python 3.5. Thanks! 

This is an awesome work. I will take a detail look.

**Comment by JasonKessler** [comment]
Really appreciate the praise, and let me know if you end up using this in a project.

BTW, demo_empath.py and demo.py now run in Python 2, although not all features in Scattertext work in py2.
