### ISSUE TITLE
Searching for term doesn't work

### ISSUE THREAD

**Issue by flyingkh** [JasonKessler/scattertext#50]
Hello this one is very useful.

I plotted speech as an example, though, 'Search for Term' doesn't work.

Recent update indicates Ver'0.0.2.43' might have an issue on this, so I re-installed it but it doesn't work, either.

Could you give me an answer with this?

(I followed exact code from example code)

Thank you,
Hoon

## Your Environment

* Operating System: Window10
* Python Version Used: 3.6
* Scattertext Version Used: 0.0.2.43
* Environment Information: Jupyter Notebook
* Browser used (if an HTML error): Chrome

**Comment by JasonKessler** [comment]
Could you please try and update to the latest version of Scattertext and see if this fixes things? I’d not, please send me the word you are searching for and some sample contexts. A screenshot of what the malfunction would also be helpful.

**Comment by JasonKessler** [comment]
if you're using the 0.0.2.62 or higher, this issue should be resolved.
