### ISSUE TITLE
issues with my data

### ISSUE THREAD

**Issue by vaidyan5** [JasonKessler/scattertext#52]
1 print(list(corpus.get_scaled_f_scores_vs_background().index[:10]))

~/anaconda3/lib/python3.7/site-packages/scattertext/TermDocMatrix.py in get_scaled_f_scores_vs_background(self, scaler_algo, beta)
    922                 pd.DataFrame of scaled_f_score scores compared to background corpus
    923 		'''
--> 924                 df = self.get_term_and_background_counts()
    925 		df['Scaled f-score'] = ScaledFScore.get_scores_for_category(
    926                         df['corpus'], df['background'], scaler_algo, beta

~/anaconda3/lib/python3.7/site-packages/scattertext/TermDocMatrix.py in get_term_and_background_counts(self)
    879 		'''
    880                 background_df = self._get_background_unigram_frequencies()
--> 881                 term_freq_df = self.get_term_freq_df()
    882                 corpus_freq_df = pd.DataFrame({'corpus': term_freq_df.sum(axis=1)})
    883                 corpus_unigram_freq = self._get_corpus_unigram_freq(corpus_freq_df)

~/anaconda3/lib/python3.7/site-packages/scattertext/TermDocMatrix.py in get_term_freq_df(self, label_append)
    160 		return pd.DataFrame(mat,
    161                                     index=pd.Series(self.get_terms(), name='term'),
--> 162 		                    columns=[c + label_append for c in self.get_categories()])
    163 
    164         def get_term_freq_mat(self):

~/anaconda3/lib/python3.7/site-packages/scattertext/TermDocMatrix.py in <listcomp>(.0)
    160 		return pd.DataFrame(mat,
    161                                     index=pd.Series(self.get_terms(), name='term'),
--> 162 		                    columns=[c + label_append for c in self.get_categories()])
    163 
    164         def get_term_freq_mat(self):

TypeError: unsupported operand type(s) for +: 'int' and 'str'

If you're seeing an HTML error, please upload a screenshot, and any Javascript errors you're
 receiving.  If possible then please upload the full HTML file if possible.

The more infor
-->

## Your Environment

* Operating System: Mac OS Catalina
* Python Version Used:3.7
* Scattertext Version Used: scattertext==0.0.2.28
* Environment Information: jupytemplate==0.3.0
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.5.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.0.2
jupyterlab-server==1.0.0

[df_test.csv.zip](https://github.com/JasonKessler/scattertext/files/4330761/df_test.csv.zip)

**Comment by JasonKessler** [comment]
Thanks for linking to your data.  What’s needed is a code snippet that I can on the latest version of Scattertext (0.0.2.59) that reproduces this error

**Comment by vaidyan5** [comment]
I believe that I had included the code snippet with the github post

**Comment by vaidyan5** [comment]
# Jason - here is the code snippet that caused the error
# Thanks...

import scattertext as st
import spacy
from pprint import pprint
nlp = spacy.load('en')

corpus = st.CorpusFromPandas(df_test,category_col='loc_k',text_col='message',nlp=nlp).build()
print(list(corpus.get_scaled_f_scores_vs_background().index[:10]))

**Comment by vaidyan5** [comment]
Just posted the code snippet..

Thanks

**Comment by JasonKessler** [comment]
Thanks! Could you please include the line(s) which create df_test?

**Comment by vaidyan5** [comment]
Here you go:


df_test.to_csv("df_test.csv", index = False)

**Comment by vaidyan5** [comment]
Just posted the line
Thanks

**Comment by JasonKessler** [comment]
Are you sure that’s how you’re generating it?

**Comment by vaidyan5** [comment]
Yes - this is how the file was generated.

Are there leading empty spaces that are causing an issue ??

Nanda

**Comment by JasonKessler** [comment]
How are you reading *in* the data frame from the csv file?

**Comment by vaidyan5** [comment]
Or is there an issue with any string and integer casting etc.??

**Comment by vaidyan5** [comment]
Using the foll:
df = pd.read_csv(“file_name”)

**Comment by JasonKessler** [comment]
Frankly, I just want to make sure that when I get to my computer, I have a snippet that I can copy and paste into python and reproduce the problem.  

I have limited resources to address these problems, and I really don’t want to spend time figuring out what you did to cause an error.

**Comment by vaidyan5** [comment]
Sure...
That’s all I did.
Thanks

Nanda

**Comment by JasonKessler** [comment]
Could you run print(st.__version__)?

**Comment by JasonKessler** [comment]
This does work for me:

>>> st.__version__
'0.0.2.59'
>>> df_test = pd.read_csv('df_test.csv')
>>> corpus = st.CorpusFromPandas(df_test,category_col='loc_k',text_col='message',nlp=nlp).build()
>>> print(list(corpus.get_scaled_f_scores_vs_background().index[:10]))
['pahahahaha', 'lexxxxxiiiiii', 'lyanna', 'lmap', 'tonighy', 'draxxxxxxxx', 'lexxx', 'bestfriend', 'sellin', 'lmao']

**Comment by vaidyan5** [comment]
Hi Jason
print(at.version)

Output is
[0 0 2 28]

Thanks

**Comment by JasonKessler** [comment]
You need to upgrade to the latest version.

**Comment by vaidyan5** [comment]
Thanks a ton for the help... Appreciate it...

Nanda.
