### ISSUE TITLE
max_snippets parameter for produce_scattertext_explorer non-functional

### ISSUE THREAD

**Issue by jmbanda** [JasonKessler/scattertext#58]
I am trying to not have the package produce any text snippets since I can't share the text being analyzed. When using max_snippets=0, nothing happens and the snippets continue to appear. The parameter seems to not be doing anything. I try max_documents=0, but this makes all the document statistics disappear. 

Thanks in advance!

* Operating System: CentOS 7
* Python Version Used: 3.69
* Scattertext Version Used: 0.0.2.63

**Comment by JasonKessler** [comment]
Thanks for the bug report.  I need to clean up the way document text is handled.

In the mean time, upgrade to the latest version of Scattertext (>=0.0.2.64) and use `    max_docs_per_category=0` as a parameter to produce_scattertext_explorer. You'll see that term statistics show up, despite no documents being included anywhere in the visualization code.

For a working example, please see https://github.com/JasonKessler/scattertext/blob/master/demo_compact_suppress_documents.py
