### ISSUE TITLE
Extracting Charts From Scattertext Explorer

### ISSUE THREAD

**Issue by fjubair** [JasonKessler/scattertext#59]
I am using a scattertext explorer for a corpus with millions of tweets. The produced html by st.produce_scattertext_explorer is too big. Is there a way to extract/show only the chart inside the html?
Thank you.

**Comment by JasonKessler** [comment]
Two things:

1. In produce_scattertext_explorer (or whatever function you're using to generate the chart), pass in max_docs_per_category=0. That will make sure that no documents are included in the chart.

2. Make sure that no more than 4,000 terms are being used to create the chart. The more terms you render, the more circles your browser has to render and the more labels Scattertext has to assign.  One way to do this is to run your corpus through an AssociationCompactor, as in the example at the top of the Readme.

Below, only the 2000 words which are most associated with either category are kept.

```
corpus = st.CorpusFromParsedDocuments(
    df, category_col='party', parsed_col='parse'
).build().get_unigram_corpus().compact(st.AssociationCompactor(2000))
```

**Comment by fjubair** [comment]
Thank you very much for your help

**Comment by fjubair** [comment]
Hello Jason,

What about Empath Visualization corpus? For example, in the below code,
adding AssociationCompactor would give me an error. Is
using AssociationCompactor not actually needed in this case? Again, my
intention is to make sure the generated html file by
the produce_scattertext_explorer is very small so that it can be rendered
by the browser.
Thank you very much.

empath_corpus = st.CorpusFromParsedDocuments(convention_df,
...                                              category_col='party',
...
feats_from_spacy_doc=feat_builder,
...                                              parsed_col='text').build()

**Comment by JasonKessler** [comment]
Hmm. I’ll have to look into why the compactor’s not working with empath, but it shouldn’t be necessary. Just make sure your max_docs_per_category is 0
