### ISSUE TITLE
ModuleNotFoundError  

### ISSUE THREAD

**Issue by Josenorte** [JasonKessler/scattertext#61]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-790e9e886490> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
----> 2 import scattertext as st
      3 import re, io
      4 from pprint import pprint
      5 import pandas as pd

ModuleNotFoundError: No module named 'scattertext'

all modules are installed

(base) MacBook-Jose-2:~ jnorte$ pip3 install matplotlib
Collecting matplotlib
  Downloading matplotlib-3.2.1-cp38-cp38-macosx_10_9_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 1.3 MB/s 
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 1.1 MB/s 
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: numpy>=1.11 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib) (1.18.5)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp38-cp38-macosx_10_9_x86_64.whl (60 kB)
     |████████████████████████████████| 60 kB 1.2 MB/s 
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from cycler>=0.10->matplotlib) (1.15.0)
Installing collected packages: cycler, pyparsing, kiwisolver, matplotlib
Successfully installed cycler-0.10.0 kiwisolver-1.2.0 matplotlib-3.2.1 pyparsing-2.4.7
(base) MacBook-Jose-2:~ jnorte$ pip3 install inline
Collecting inline
  Downloading inline-0.0.1.tar.gz (2.7 kB)
Using legacy setup.py install for inline, since package 'wheel' is not installed.
Installing collected packages: inline
    Running setup.py install for inline ... done
Successfully installed inline-0.0.1
(base) MacBook-Jose-2:~ jnorte$ pip3 install scattertext
Requirement already satisfied: scattertext in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (0.0.2.65)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.18.5)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.15.0)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (0.23.1)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.0.4)
Requirement already satisfied: statsmodels in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (0.11.1)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.4.1)
Requirement already satisfied: mock in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (4.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn->scattertext) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn->scattertext) (0.15.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas->scattertext) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas->scattertext) (2020.1)
Requirement already satisfied: patsy>=0.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from statsmodels->scattertext) (0.5.1)
##################################################################

python3 --version
Python 3.7.6

## Your Environment

* Operating System:
* Python Version Used:
* Scattertext Version Used:
* Environment Information:
* Browser used (if an HTML error):

**Comment by Josenorte** [comment]
looks like all OK ?

(base) MacBook-Jose-2:~ jnorte$ pip3 install -U scattertext
Requirement already up-to-date: scattertext in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (0.0.2.65)
Requirement already satisfied, skipping upgrade: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.15.0)
Requirement already satisfied, skipping upgrade: pandas in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.0.4)
Requirement already satisfied, skipping upgrade: statsmodels in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (0.11.1)
Requirement already satisfied, skipping upgrade: mock in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (4.0.2)
Requirement already satisfied, skipping upgrade: numpy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.18.5)
Requirement already satisfied, skipping upgrade: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (0.23.1)
Requirement already satisfied, skipping upgrade: scipy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scattertext) (1.4.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas->scattertext) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas->scattertext) (2020.1)
Requirement already satisfied, skipping upgrade: patsy>=0.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from statsmodels->scattertext) (0.5.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn->scattertext) (0.15.1)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn->scattertext) (2.1.0)

**Comment by JasonKessler** [comment]
Are you still the same error?

**Comment by Josenorte** [comment]
Yes :(

%matplotlib inline
import scattertext as st
import re, io
from pprint import pprint
import pandas as pd
import numpy as np
from scipy.stats import rankdata, hmean, norm
import spacy
import os, pkgutil, json, urllib
from urllib.request import urlopen
from IPython.display import IFrame
from IPython.core.display import display, HTML
from scattertext import CorpusFromPandas, produce_scattertext_explorer
display(HTML("<style>.container { width:98% !important; }</style>"))
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-790e9e886490> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
----> 2 import scattertext as st
      3 import re, io
      4 from pprint import pprint
      5 import pandas as pd

ModuleNotFoundError: No module named 'scattertext'

**Comment by JasonKessler** [comment]
You may want to make sure your notebook is running in the correct virtual
environment, and you’re using the pip command belonging to that environment
