### ISSUE TITLE
Saving CorpusDF object

### ISSUE THREAD

**Issue by scottkleinman** [JasonKessler/scattertext#62]
Is there a method for serialising a CorpusDF object to disk and reloading it later? That could be a real time saver, but I can't seem to find one.

**Comment by JasonKessler** [comment]
You should be able to use joblib.dump and joblib.save to serialize and deserialize CorpusDF and ParsedCorpus objects.

**Comment by scottkleinman** [comment]
Yes, that works. Thanks!
