### ISSUE TITLE
<Question> How can we use embedding of conceptnet numberbatch here? 

### ISSUE THREAD

**Issue by vijender412** [JasonKessler/scattertext#66]
First of all, thanks for sharing the one of the greatest open sourced work. 
I have gone through the package and found very useful. Going one step more I wanted to try conceptnet numberbatch or bert embedding in this. Can you suggest any way. 
Thanks

**Comment by JasonKessler** [comment]
Right now, the means of visualizing scatterplots of arbitrary term or document embeddings projected into 2d is a little janky. I'd suggest taking a look at demo_embeddings_pca.py and tracing through that code.

**Comment by vijender412** [comment]
Thanks alot @JasonKessler . I would like to take time and try some of the embedding and will get back to you on this thread.

**Comment by JasonKessler** [comment]
Best of luck!
