### ISSUE TITLE
How to filter out category using search term ?

### ISSUE THREAD

**Issue by Kavan72** [JasonKessler/scattertext#74]
Hey @JasonKessler 

how could we improve the library so that when a user is searching for a specific term, then the categories not containing the word would be removed from the graph and from the listing beneath the graph?

we want basically to enhance it so that the user has a filter in and filter out possibility which would be automatically reflected in the graph.

## My Environment
* Operating System: Ubuntu 18.04
* Python Version Used: 3.7
* Scattertext Version Used: Latest(github version)

**Comment by JasonKessler** [comment]
Could you please include an example of what's happening now and what you'd like to see?

**Comment by ursachi** [comment]
Hi Jason, it is not an issue per se, but an enhancement we would like to do. That is when someone is searching for a term, all categories not including that term should be not shown. Moreover the words belonging to the excluded categories but that are not in the remaining categories should be removed from the graph. See image below

<img width="942" alt="image" src="https://user-images.githubusercontent.com/841042/99883166-e9a13380-2c25-11eb-8da6-43998e145331.png">

The idea is that we want to help user visualize better what categories and sub-categories match to words or texts input by them and have the possibility to filter out while they understand better the context.

**Comment by JasonKessler** [comment]
If I understand the request, correct, you'd want to the system to eliminate document categories (i.e., the political parties above) and topics (the general inquirer categories in your example) which don't contain it?

That sounds interesting, but it's not something I have the bandwidth to do.

If you'd like the feature implemented, I'd encourage you to modify main.js which is where the relevant javascript is. I'd be happy to help integrate those additions into Scattertext.

**Comment by ursachi** [comment]
yes, the idea was to know where to do it, and we may give it a try
