### ISSUE TITLE
Is there  a way to store the top scored documents in a seperate dataframe for each category?

### ISSUE THREAD

**Issue by Alisha1992** [JasonKessler/scattertext#75]
![image](https://user-images.githubusercontent.com/39727112/101507829-fef3bd00-399c-11eb-928b-b2db861c0529.png)

Hi Jason,

Could you please let me know **if there is a way to store the documents generated for each word in the category**  as of now in this current package?? Please reply ASAP. 

Is there is any particular method name to get the documents for each word in the category??

Your help would be appreciated.

Thanks,
Alisha Panda

**Comment by JasonKessler** [comment]
You can run the search(str) function on a ParsedCorpus instance (built by CorpusFromParsedDocuments) to get a data frame with all matching documents. 

If you'd like the exact text returned in the UI, you'll have to modify the Javascript code.
