### ISSUE TITLE
How to interpret the scattertext phrase machine plot?

### ISSUE THREAD

**Issue by Alisha1992** [JasonKessler/scattertext#79]
Hi Jasson,

I have couple of questions about scattertext phrase visulation plot. 
Q1) How to interpret the different colors used in the plot like dark blue, light blue, yellow, dark red, etc?
Q2) How to interpret the various scores i.e. positive value score and negative value scores along the axes and its relatability??

Your quick response would really be of great help.

Best,
Alisha Panda

**Comment by JasonKessler** [comment]
The point colors correspond to the values in the score parameter, or the rank difference score, by default. The term positions roughly correspond to frequency rank of a term within that axis' category.
