### ISSUE TITLE
Is there a way to get those Phrases plotted as points in the graph?? 

### ISSUE THREAD

**Issue by Alisha1992** [JasonKessler/scattertext#86]
Hi Jasson,

Is there any possibility to get the phrases plotted in the graph as a metadata ??  I am using PhraseMachine to build the graph. It would be of great help if there is a way to get the phrases.

Example: When any point clicked in the graph, the reviews appears . I want the highlighted text like (barack obama ) as tags next to each of the reviews

Your quick response will be of great help.

Best,
Alisha Panda

**Comment by JasonKessler** [comment]
Currently, no. Maybe in the future.
