### ISSUE TITLE
Not list out the snippets

### ISSUE THREAD

**Issue by lampts** [JasonKessler/scattertext#9]
Thank for such a wonderful tool to do visualisation.

I got the error after running on small dataset as attached. There are 1 mention including apple term but the snippets on current is empty.

<img width="1141" alt="screen shot 2017-03-13 at 2 47 43 pm" src="https://cloud.githubusercontent.com/assets/656949/23845739/7d71c752-07fc-11e7-9d29-47a45e66279a.png">

What's wrong with that?
Regards,
Laam

**Comment by JasonKessler** [comment]
Hi Laam,

Thanks for reporting this error, and for the compliment!

I'm having trouble seeing the attached dataset.  It would be great if you could upload the actual HTML file produced.

The mention counts displayed on the visualization were determined in Python via spaCy's (or whatever NLP engine you used's) tokenizer, while the excerpts listed are found through a Javascript regex, which may be less robust to special characters.  

Jason

**Comment by lampts** [comment]
Yes, it seems the mismatched between mentions by spacy and javascript regex to get related snippets. I can share you another file which has the same issue:
(1) query exxon: there is no snippets related to the Past (x axis)
(2) terms: brexit, ipo are not clickable

The attached is for reproducible.

[FINZINE-Visualization-trendy-vs-past-v2.html.zip](https://github.com/JasonKessler/scattertext/files/840478/FINZINE-Visualization-trendy-vs-past-v2.html.zip)

**Comment by JasonKessler** [comment]
Thanks a lot for including the full output.  That really helped in debugging this issue.  I found it, and there will be a fix in the next release (which is coming in a few minutes).
