### ISSUE TITLE
AttributeError: module 'pytextrank' has no attribute 'TextRank'

### ISSUE THREAD

**Issue by Anthonyive** [JasonKessler/scattertext#92]
## Steps to Reproduce

```python
corpus = st.CorpusFromParsedDocuments(
    convention_df,
    category_col='category',
    parsed_col='parse',
    feats_from_spacy_doc=st.PyTextRankPhrases()
).build(
).compact(
    AssociationCompactor(2000, use_non_text_features=True)
)
```

### Error:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

...

~/.local/share/virtualenvs/.../lib/python3.8/site-packages/scattertext/features/PyTextRankPhrases.py in get_doc_metadata(self, doc)
     32         import pytextrank
     33         phrase_counter = Counter()
---> 34         tr = pytextrank.TextRank()
     35         tr.doc = doc
     36         phrases = tr.calc_textrank()

AttributeError: module 'pytextrank' has no attribute 'TextRank'
```

## Expected behavior

No error.

## Environment

 - Scattertext version (e.g., 0.0.2.75): 0.1.0.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): `pipenv`
 - Python version: 3.8
 - Any other relevant information: spacy 3.0.1

## Additional context

Looks like `pytextrank` no longer has the attribute `TextRank`. Maybe you should change the code in `scattertext/features/PyTextRankPhrases.py` from `tr = pytextrank.TextRank()` to spacy pipeline.

**Comment by JasonKessler** [comment]
Thanks for the bug report. I ran into some issues using PyTextRank to parse multiple documents with the same spaCy Language instance. Not sure if these persist in PTR v3, but the easiest thing to do would be to explicitly use an earlier version.

**Comment by JasonKessler** [comment]
I just released v0.1.2 which enables Scattertext to work with PTR v3. The results on the convention data set look a little better using the new version.

**Comment by JasonKessler** [comment]
It looks like the spaCy documentation isn't current with the latest version
of PyTextRank. You may want to raise an issue with them.

Scattertext's documentation, however, is current. Please follow that.

**Comment by Dopamine-TX** [comment]
nlp.add_pipe("textrank")
